# Generated by Django 4.2.2 on 2023-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
