# Generated by Django 4.2.2 on 2023-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tarefas', '0003_alter_tarefas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
