# Generated by Django 4.2.2 on 2023-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tarefas', '0004_alter_tarefas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
