# Generated by Django 4.2.2 on 2023-07-18 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_de_tarefas', '0005_alter_tarefas_descricao_alter_tarefas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
