# Generated by Django 4.2.2 on 2023-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tarefas', '0006_tarefas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(blank=True, error_messages='Erro : O maximo de caracter é 200', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='titulo',
            field=models.CharField(error_messages='Erro : O maximo de caracter é 50', max_length=50),
        ),
    ]
